### ISSUE TITLE
feature: 배정 결과 페이지

### ISSUE THREAD

**Issue by Jnayun** [capstone-design-Fkiller/client#36]
## 💡 Issue
사물함 배정 결과 페이지

## 📝 todo
- [x] (관리자 학과에 한정된) 사물함 배정 결과 가져오기(API)
- [x] 디자인: 공지사항 페이지 수정해서 제작하기
- [x] 맘에 안 드는 사람 삭제하기
