### ISSUE TITLE
feature: 관리자 배정 기준 신청 페이지 구현하기

### ISSUE THREAD

**Issue by urjimyu** [capstone-design-Fkiller/client#37]
## 💡 Issue

관리자 뷰에서 배정하기 버튼을 누르면 연결되는 배정 기준 등록 페이지를 구현합니다.

## 📝 todo

- [x] 배정 기준 입력 UI 만들기
- [x] 기준 미기입시 선착순으로 세팅하기
- [x] 배정 기준 입력 후 확인 버튼 누르면 서버에서 PUT 보내기
